vti/dashboard/src/main/java/com/android/vts/servlet/DashboardMainServlet.java
/*
 * Copyright (c) 2016 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.android.vts.servlet;

import com.android.vts.entity.TestEntity;
import com.android.vts.entity.TestStatusEntity;
import com.android.vts.entity.UserFavoriteEntity;
import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.DatastoreServiceFactory;
import com.google.appengine.api.datastore.Entity;
import com.google.appengine.api.datastore.Key;
import com.google.appengine.api.datastore.KeyFactory;
import com.google.appengine.api.datastore.PropertyProjection;
import com.google.appengine.api.datastore.Query;
import com.google.appengine.api.datastore.Query.Filter;
import com.google.appengine.api.datastore.Query.FilterOperator;
import com.google.appengine.api.datastore.Query.FilterPredicate;
import com.google.appengine.api.users.User;
import com.google.appengine.api.users.UserService;
import com.google.appengine.api.users.UserServiceFactory;
import com.google.gson.Gson;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.stream.Collectors;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import static com.googlecode.objectify.ObjectifyService.ofy;

/** Represents the servlet that is invoked on loading the first page of dashboard. */
public class DashboardMainServlet extends BaseServlet {
    private static final String DASHBOARD_MAIN_JSP = "WEB-INF/jsp/dashboard_main.jsp";
    private static final String NO_TESTS_ERROR = "No test results available.";

    @Override
    public PageType getNavParentType() {
        return PageType.TOT;
    }

    @Override
    public List<Page> getBreadcrumbLinks(HttpServletRequest request) {
        return null;
    }

    /** Helper class for displaying test entries on the main dashboard. */
    public class TestDisplay implements Comparable<TestDisplay> {
        private final Key testKey;
        private final int passCount;
        private final int failCount;
        private boolean muteNotifications;
        private boolean isFavorite;

        /**
         * Test display constructor.
         *
         * @param testKey The key of the test.
         * @param passCount The number of tests passing.
         * @param failCount The number of tests failing.
         * @param muteNotifications The flag for user notification in case of test failure.
         * @param isFavorite The flag for showing favorite mark on All Tests Tab page.
         */
        public TestDisplay(
                Key testKey,
                int passCount,
                int failCount,
                boolean muteNotifications,
                boolean isFavorite) {
            this.testKey = testKey;
            this.passCount = passCount;
            this.failCount = failCount;
            this.muteNotifications = muteNotifications;
            this.isFavorite = isFavorite;
        }

        /**
         * Get the key of the test.
         *
         * @return The key of the test.
         */
        public String getName() {
            return this.testKey.getName();
        }

        /**
         * Get the number of passing test cases.
         *
         * @return The number of passing test cases.
         */
        public int getPassCount() {
            return this.passCount;
        }

        /**
         * Get the number of failing test cases.
         *
         * @return The number of failing test cases.
         */
        public int getFailCount() {
            return this.failCount;
        }

        /**
         * Get the notification mute status.
         *
         * @return True if the subscriber has muted notifications, false otherwise.
         */
        public boolean getMuteNotifications() {
            return this.muteNotifications;
        }

        /** Set the notification mute status. */
        public void setMuteNotifications(boolean muteNotifications) {
            this.muteNotifications = muteNotifications;
        }

        /**
         * Get the favorate status.
         *
         * @return True if an user set favorate for the test, false otherwise.
         */
        public boolean getIsFavorite() {
            return this.isFavorite;
        }

        /** Set the favorite status. */
        public void setIsFavorite(boolean isFavorite) {
            this.isFavorite = isFavorite;
        }

        @Override
        public int compareTo(TestDisplay test) {
            return this.testKey.getName().compareTo(test.getName());
        }
    }

    @Override
    public void doGetHandler(HttpServletRequest request, HttpServletResponse response)
            throws IOException {
        UserService userService = UserServiceFactory.getUserService();
        User currentUser = userService.getCurrentUser();
        RequestDispatcher dispatcher = null;
        DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
        HttpSession session = request.getSession(true);
        PageType referTo = PageType.TREE;
        if (session.getAttribute("treeDefault") != null) {
            boolean treeDefault = (boolean) session.getAttribute("treeDefault");
            if (!treeDefault) {
                referTo = PageType.TABLE;
            }
        }

        List<TestDisplay> displayedTests = new ArrayList<>();
        List<Key> unprocessedTestKeys = new ArrayList<>();

        Map<Key, TestDisplay> testMap = new HashMap<>(); // map from table key to TestDisplay
        Map<String, String> subscriptionMap = new HashMap<>();

        boolean showAll = request.getParameter("showAll") != null;
        String error = null;

        List<String> allTestNames = TestEntity.getAllTestNames();

        List<Key> favoriteKeyList = new ArrayList<Key>();
        Filter userFilter =
                new FilterPredicate(UserFavoriteEntity.USER, FilterOperator.EQUAL, currentUser);
        Query filterQuery = new Query(UserFavoriteEntity.KIND).setFilter(userFilter);
        Iterable<Entity> favoriteIter = datastore.prepare(filterQuery).asIterable();
        favoriteIter.forEach(
                fe -> {
                    Key testKey = UserFavoriteEntity.fromEntity(fe).testKey;
                    favoriteKeyList.add(testKey);
                    subscriptionMap.put(testKey.getName(), KeyFactory.keyToString(fe.getKey()));
                });

        Query query =
                new Query(TestStatusEntity.KIND)
                        .addProjection(
                                new PropertyProjection(TestStatusEntity.PASS_COUNT, Long.class))
                        .addProjection(
                                new PropertyProjection(TestStatusEntity.FAIL_COUNT, Long.class));
        for (Entity status : datastore.prepare(query).asIterable()) {
            TestStatusEntity statusEntity = TestStatusEntity.fromEntity(status);
            if (statusEntity == null) continue;
            Key testKey = KeyFactory.createKey(TestEntity.KIND, statusEntity.getTestName());
            boolean isFavorite = favoriteKeyList.contains(testKey);
            TestDisplay display = new TestDisplay(testKey, -1, -1, false, isFavorite);
            if (!unprocessedTestKeys.contains(testKey)) {
                display =
                        new TestDisplay(
                                testKey,
                                statusEntity.getPassCount(),
                                statusEntity.getFailCount(),
                                false,
                                isFavorite);
            }
            testMap.put(testKey, display);
        }

        if (testMap.size() == 0) {
            error = NO_TESTS_ERROR;
        }

        if (showAll) {
            for (Key testKey : testMap.keySet()) {
                displayedTests.add(testMap.get(testKey));
            }
        } else {
            if (testMap.size() > 0) {
                for (Entity favoriteEntity : favoriteIter) {
                    UserFavoriteEntity favorite = UserFavoriteEntity.fromEntity(favoriteEntity);
                    Key testKey = favorite.testKey;
                    if (!testMap.containsKey(testKey)) {
                        continue;
                    }
                    TestDisplay display = testMap.get(testKey);
                    display.setMuteNotifications(favorite.muteNotifications);
                    displayedTests.add(display);
                }
            }
        }
        displayedTests.sort(Comparator.naturalOrder());

        response.setStatus(HttpServletResponse.SC_OK);
        request.setAttribute("allTestsJson", new Gson().toJson(allTestNames));
        request.setAttribute("subscriptionMapJson", new Gson().toJson(subscriptionMap));
        request.setAttribute("testNames", displayedTests);
        request.setAttribute("showAll", showAll);
        request.setAttribute("error", error);
        request.setAttribute("resultsUrl", referTo.defaultUrl);
        dispatcher = request.getRequestDispatcher(DASHBOARD_MAIN_JSP);
        try {
            dispatcher.forward(request, response);
        } catch (ServletException e) {

vti/dashboard/src/main/java/com/android/vts/servlet/ShowCoverageServlet.java
/*
 * Copyright (c) 2016 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.android.vts.servlet;

import static com.googlecode.objectify.ObjectifyService.ofy;

import com.android.vts.entity.CoverageEntity;
import com.android.vts.entity.RoleEntity;
import com.android.vts.entity.TestEntity;
import com.android.vts.entity.TestRunEntity;
import com.android.vts.entity.UserEntity;
import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.DatastoreServiceFactory;
import com.google.appengine.api.datastore.Entity;
import com.google.appengine.api.datastore.Key;
import com.google.appengine.api.datastore.KeyFactory;
import com.google.appengine.api.datastore.Query;
import com.google.gson.Gson;
import com.googlecode.objectify.Ref;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.logging.Level;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet for handling requests to show code coverage.
 */
public class ShowCoverageServlet extends BaseServlet {

  private static final String COVERAGE_JSP = "WEB-INF/jsp/show_coverage.jsp";
  private static final String TREE_JSP = "WEB-INF/jsp/show_tree.jsp";

  @Override
  public PageType getNavParentType() {
    return PageType.TOT;
  }

  @Override
  public List<Page> getBreadcrumbLinks(HttpServletRequest request) {
    List<Page> links = new ArrayList<>();
    String testName = request.getParameter("testName");
    links.add(new Page(PageType.TABLE, testName, "?testName=" + testName));

    String startTime = request.getParameter("startTime");
    links.add(new Page(PageType.COVERAGE, "?testName=" + testName + "&startTime=" + startTime));
    return links;
  }

  @Override
  public void doGetHandler(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    RequestDispatcher dispatcher = null;

    String test = request.getParameter("testName");
    String timeString = request.getParameter("startTime");

    Boolean isModerator = false;
    String currentUserEmail = request.getAttribute("email").toString();
    Optional<UserEntity> userEntityOptional = Optional
        .ofNullable(UserEntity.getUser(currentUserEmail));
    if (userEntityOptional.isPresent()) {
      Ref refRole = Ref.create(RoleEntity.getRole("coverage-moderator"));
      isModerator = userEntityOptional.get().getRoles().contains(refRole);
    }

    // Process the time key requested
    long time = -1;
    try {
      time = Long.parseLong(timeString);
    } catch (NumberFormatException e) {
      request.setAttribute("testName", test);
      dispatcher = request.getRequestDispatcher(TREE_JSP);
      return;
    }

    com.googlecode.objectify.Key testKey = com.googlecode.objectify.Key
        .create(TestEntity.class, test);
    com.googlecode.objectify.Key testRunKey = com.googlecode.objectify.Key
        .create(testKey, TestRunEntity.class, time);

    List<CoverageEntity> coverageEntityList = ofy().load().type(CoverageEntity.class)
        .ancestor(testRunKey).list();

    Collections.sort(coverageEntityList, CoverageEntity.isIgnoredComparator);

    request.setAttribute("isModerator", isModerator);
    request.setAttribute("testName", request.getParameter("testName"));
    request.setAttribute("gerritURI", new Gson().toJson(GERRIT_URI));
    request.setAttribute("gerritScope", new Gson().toJson(GERRIT_SCOPE));
    request.setAttribute("clientId", new Gson().toJson(CLIENT_ID));
    request.setAttribute("startTime", request.getParameter("startTime"));
    request.setAttribute("coverageEntityList", coverageEntityList);

    dispatcher = request.getRequestDispatcher(COVERAGE_JSP);
    try {
      dispatcher.forward(request, response);
    } catch (ServletException e) {
      logger.log(Level.SEVERE, "Servlet Exception caught : ", e);
    }
  }
}

vti/dashboard/src/main/java/com/android/vts/servlet/ShowProfilingListServlet.java
/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You may
 * obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.android.vts.servlet;

import static com.googlecode.objectify.ObjectifyService.ofy;

import com.android.vts.entity.TestEntity;
import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.DatastoreServiceFactory;
import com.google.appengine.api.datastore.Entity;
import com.google.appengine.api.datastore.Query;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.stream.Collectors;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet for handling requests to display profiling tests.
 */
public class ShowProfilingListServlet extends BaseServlet {

  private static final String PROFILING_LIST_JSP = "WEB-INF/jsp/show_profiling_list.jsp";

  @Override
  public PageType getNavParentType() {
    return PageType.PROFILING_LIST;
  }

  @Override
  public List<Page> getBreadcrumbLinks(HttpServletRequest request) {
    return null;
  }

  @Override
  public void doGetHandler(HttpServletRequest request, HttpServletResponse response)
      throws IOException {
    List<String> tests = ofy().load().type(TestEntity.class)
        .filter(TestEntity.HAS_PROFILING_DATA, true).list().stream()
        .sorted(Comparator.comparing(TestEntity::getTestName)).map(t -> t.getTestName())
        .collect(Collectors.toList());

    response.setStatus(HttpServletResponse.SC_OK);
    request.setAttribute("testNames", tests);
    RequestDispatcher dispatcher = request.getRequestDispatcher(PROFILING_LIST_JSP);
    try {
      dispatcher.forward(request, response);
    } catch (ServletException e) {
      logger.log(Level.SEVERE, "Servlet Excpetion caught : ", e);
    }
  }
}

vti/dashboard/src/main/webapp/WEB-INF/jsp/error_msg.jsp
<%--
  ~ Copyright (c) 2018 Google Inc. All Rights Reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License"); you
  ~ may not use this file except in compliance with the License. You may
  ~ obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
  ~ implied. See the License for the specific language governing
  ~ permissions and limitations under the License.
  --%>
<%@ page contentType='text/html;charset=UTF-8' language='java' %>
<%@ taglib prefix='fn' uri='http://java.sun.com/jsp/jstl/functions' %>
<%@ taglib prefix='c' uri='http://java.sun.com/jsp/jstl/core'%>

<html>
<link rel='stylesheet' href='/css/dashboard_main.css'>
<%@ include file='header.jsp' %>
<body>

<div class='container wide'>

    <div class="card-panel">
        <span class="red-text text-darken-2">
          <h3> <c:out value="${error_title}"></c:out> </h3>
          <br/>
          <c:out value="${error_message}"></c:out>
        </span>
    </div>

</div>
<%@ include file='footer.jsp' %>
</body>
</html>

vti/dashboard/src/main/webapp/WEB-INF/jsp/footer.jsp
<%--
  ~ Copyright (c) 2017 Google Inc. All Rights Reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License"); you
  ~ may not use this file except in compliance with the License. You may
  ~ obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
  ~ implied. See the License for the specific language governing
  ~ permissions and limitations under the License.
  --%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<footer class="page-footer" style="height: 70px;">
  <div class="footer-copyright">
    <div class="container">
      © 2017 - The Android Open Source Project
    </div>
  </div>
</footer>

vti/dashboard/src/main/webapp/WEB-INF/jsp/header.jsp
<%--
  ~ Copyright (c) 2017 Google Inc. All Rights Reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License"); you
  ~ may not use this file except in compliance with the License. You may
  ~ obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
  ~ implied. See the License for the specific language governing
  ~ permissions and limitations under the License.
  --%>
<%@ page contentType='text/html;charset=UTF-8' language='java' %>
<%@ taglib prefix='c' uri='http://java.sun.com/jsp/jstl/core'%>

<head>
  <link rel='stylesheet' href='https://www.gstatic.com/external_hosted/materialize/all_styles-bundle.css'>
  <link rel='icon' href='https://www.gstatic.com/images/branding/googleg/1x/googleg_standard_color_32dp.png' sizes='32x32'>
  <link rel='stylesheet' href='https://fonts.googleapis.com/icon?family=Material+Icons'>
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700'>
  <link rel='stylesheet' href='/css/navbar.css'>
  <link rel='stylesheet' href='/css/common.css'>
  <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
  <script src='https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js'></script>
  <script src='https://www.gstatic.com/external_hosted/materialize/materialize.min.js'></script>
  <script type='text/javascript'>
    if (${analyticsID}) {
        // Autogenerated from Google Analytics
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        ga('create', ${analyticsID}, 'auto');
        ga('send', 'pageview');
    }
  </script>
  <title>VTS Dashboard</title>
</head>
<body>
  <nav id='navbar'>
    <div class='nav-wrapper'>
      <a href='#' class='brand-logo center'>VTS Dashboard</a>
      <ul class='nav-list'>
        <c:forEach items='${navbarLinks}' var='link' varStatus='loop'>
          <li class='${loop.index == activeIndex ? "active" : ""}'>
            <a class='nav-list-item' href='${link.url}'>${link.name}</a>
          </li>
        </c:forEach>
      </ul>
      <ul class='right'><li>
        <a id='dropdown-button' class='dropdown-button btn red lighten-3' href='#' data-activates='dropdown'>
          ${email}
        </a>
      </li></ul>
      <ul id='dropdown' class='dropdown-content'>
        <li><a href='${logoutURL}'>Log out</a></li>
      </ul>
      <c:if test='${breadcrumbLinks != null}'>
        <div id='nav-sublist'>
          <c:forEach items='${breadcrumbLinks}' var='link'>
            <a href='${link.url}' class='nav-sublist-item breadcrumb'>${link.name}</a>
          </c:forEach>
        </div>
      </c:if>
    </div>
  </nav>
</body>

vti/dashboard/src/main/webapp/WEB-INF/jsp/show_gcs_log.jsp
<%--
  ~ Copyright (c) 2018 Google Inc. All Rights Reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License"); you
  ~ may not use this file except in compliance with the License. You may
  ~ obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
  ~ implied. See the License for the specific language governing
  ~ permissions and limitations under the License.
  --%>
<%@ page contentType='text/html;charset=UTF-8' language='java' %>
<%@ taglib prefix='fn' uri='http://java.sun.com/jsp/jstl/functions' %>
<%@ taglib prefix='c' uri='http://java.sun.com/jsp/jstl/core'%>

<html>
  <%@ include file="header.jsp" %>
  <link rel='stylesheet' href='/css/show_gcs_log.css'>
  <link rel='stylesheet' href='/css/search_header.css'>
  <script src='https://www.gstatic.com/external_hosted/moment/min/moment-with-locales.min.js'></script>
  <script src='js/time.js'></script>
  <script src='js/plan_runs.js'></script>
  <script src='js/search_header.js'></script>
  <script type='text/javascript'>
      $(document).ready(function() {
        var paraMap = {'path': '', 'entry': ''};
        $('.modal').modal({
          dismissible: true,  // Modal can be dismissed by clicking outside of the modal
          opacity: .5,  // Opacity of modal background
          inDuration: 300,  // Transition in duration
          outDuration: 200,  // Transition out duration
          startingTop: '4%',  // Starting top style attribute
          endingTop: '10%',  // Ending top style attribute
          ready: function(modal, trigger) {  // Callback for Modal open. Modal and trigger parameters available.
            $('.loading-overlay').show();
            if ($(modal).attr("id") == "logEntryListModal") {
              console.log($(trigger));
              $(trigger).addClass("active");
              paraMap['path'] = "${path}" + trigger.text().trim();
              var fileName = paraMap['path'].substring(paraMap['path'].lastIndexOf('/')+1);  // Getting filename
              $(modal).find('#entry-list-modal-title').text(fileName);  // Set file name for modal window
              var url = "${requestScope['javax.servlet.forward.servlet_path']}?path=" + paraMap['path'];
              $(modal).find('#downloadLink').prop('href', url + "&action=download");
              $.get( url, function(data) {
                var entryList = $(modal).find('#modal-entry-list');
                $(data.entryList).each(function( index, element ) {
                  entryList.append("<li class='collection-item'><a href='#logEntryViewModal' class='modal-trigger'>" + element + "</a></li>");
                });
              }).done(function() {
                  $('.loading-overlay').hide();
              });
            } else {
              paraMap['entry'] = trigger.text().trim();
              $(modal).find('#entry-view-modal-title').text(paraMap['entry']);
              var entryUrl = "${requestScope['javax.servlet.forward.servlet_path']}?path=" + paraMap['path'] + "&entry=" + paraMap['entry'];
              $.get( entryUrl, function(data) {
                $(modal).find('#entry-view-modal-content').text(data.entryContent);
              }).done(function() {
                $('.loading-overlay').hide();
              });
            }
          },
          complete: function(modal) {
              if ($(modal).attr("id") == "logEntryListModal") {
                  $(modal).find('#modal-entry-list').find("li").remove();
                  $("div.collection > a.collection-item.active").removeClass('active')
              } else {
                  $(modal).find('#entry-view-modal-content').text('');
              }
          }  // Callback for Modal close
        });
      });
  </script>

  <body>
    <div class='wide container'>
      <div class='row' id='release-container'>
        <h5>Current Directory Path : ${path}</h5>
        <hr/>
        <div class="row">
          <div class="col s7">
            <h4>Directory List</h4>
            <ul class="collection">
            <c:forEach varStatus="dirLoop" var="dirName" items="${dirList}">
              <li class="collection-item">
                <a href="${requestScope['javax.servlet.forward.servlet_path']}?path=${dirName}">
                  <c:out value="${dirName}"></c:out>
                  <c:if test="${dirLoop.first && path ne '/'}">
                    (Move to Parent)
                  </c:if>
                </a>
              </li>
              <c:if test="${!dirLoop.last}">
              </c:if>
            </c:forEach>
            </ul>
          </div>
          <div class="col s5">
            <h4>File List</h4>
            <div class="collection">
            <c:forEach varStatus="fileLoop" var="fileName" items="${fileList}">
              <a href="#logEntryListModal" class="collection-item modal-trigger">
                <c:out value="${fileName}"></c:out>
              </a>
              <c:if test="${!fileLoop.last}">
              </c:if>
            </c:forEach>
            </div>
          </div>
        </div>

      </div>
    </div>

    <%@ include file="footer.jsp" %>

    <!-- Modal For Zip file entries -->
    <div id="logEntryListModal" class="modal">
      <div class="modal-content">
        <h4 id="entry-list-modal-title" class="truncate"></h4>
        <div id="entry-list-modal-content">
          <ul id="modal-entry-list" class="collection"></ul>
        </div>
      </div>
      <div class="modal-footer">
        <div class="row">
          <div class="col s3 offset-s6">
            <a href="#!" id="downloadLink" class="modal-action modal-close waves-effect waves-green btn">Download</a>
          </div>
          <div class="col s3">
            <a href="#!" class="modal-action modal-close waves-effect waves-green btn">Close</a>
          </div>
        </div>
      </div>

      <div class="loading-overlay">
        <div class="preloader-wrapper big active" style="top: 25%; left: 45%;">
          <div class="spinner-layer spinner-blue-only">
            <div class="circle-clipper left">
              <div class="circle"></div>
            </div>
            <div class="gap-patch">
              <div class="circle"></div>
            </div>
            <div class="circle-clipper right">
              <div class="circle"></div>
            </div>
          </div>
        </div>
      </div>

    </div>

    <!-- Modal For Zip file entry's content -->
    <div id="logEntryViewModal" class="modal modal-fixed-footer">
      <div class="modal-content">
        <h4 id="entry-view-modal-title" class="truncate"></h4>
        <div id="entry-view-modal-content">

        </div>
      </div>
      <div class="modal-footer">
        <a href="#!" class="modal-action modal-close waves-effect waves-green btn">Close</a>
      </div>

      <div class="loading-overlay">
        <div class="preloader-wrapper big active" style="top: 25%; left: 45%;">
          <div class="spinner-layer spinner-blue-only">
            <div class="circle-clipper left">
              <div class="circle"></div>
            </div>
            <div class="gap-patch">
              <div class="circle"></div>
            </div>
            <div class="circle-clipper right">
              <div class="circle"></div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </body>
</html>